services:
  # Production PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: comfyrent-postgres
    environment:
      POSTGRES_DB: comfyrent_production
      POSTGRES_USER: comfyrent_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./back-end/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./backups:/backups
    ports:
      - "5432:5432"
    networks:
      - comfyrent-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U comfyrent_user -d comfyrent_production"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '0.4'
        reservations:
          memory: 1G
          cpus: '0.2'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Redis for caching and session management
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: comfyrent-redis
    secrets:
      - redis_password
    volumes:
      - redis_data:/data
    networks:
      - comfyrent-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli -a $(cat /run/secrets/redis_password) ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # MinIO S3-compatible storage
  minio:
    image: minio/minio:RELEASE.2024-01-16T16-07-38Z
    container_name: comfyrent-minio
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minio_root_user
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_root_password
    secrets:
      - minio_root_user
      - minio_root_password
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - comfyrent-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Production Backend API
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile.production
      args:
        - BUILD_ENV=production
    container_name: comfyrent-backend
    env_file:
      - .env.production
    environment:
      # Worker configuration for better performance
      - WORKERS=4
      - WORKER_CLASS=uvicorn.workers.UvicornWorker
      - MAX_REQUESTS=1000
      - MAX_REQUESTS_JITTER=50
      - TIMEOUT=60
    ports:
      - "8000:8000"
    secrets:
      - postgres_password
      - minio_root_password
      - jwt_secret_key
      - redis_password
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - comfyrent-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '0.4'
        reservations:
          memory: 1G
          cpus: '0.2'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Production Frontend
  frontend:
    build:
      context: ./renting-front
      dockerfile: Dockerfile.production
      args:
        - BUILD_ENV=production
    container_name: comfyrent-frontend
    env_file:
      - renting-front/.env.production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - comfyrent-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Background Task Worker (for heavy backend operations)
  backend_worker:
    build:
      context: ./back-end
      dockerfile: Dockerfile.production
      args:
        - BUILD_ENV=production
    environment:
      # Worker mode configuration
      - WORKER_MODE=true
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - CONCURRENCY=2
    env_file:
      - .env.production
    secrets:
      - postgres_password
      - minio_root_password
      - jwt_secret_key
      - redis_password
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - comfyrent-network
    restart: unless-stopped
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
          cpus: '0.2'
        reservations:
          memory: 512M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Production Scraper (Refactored)
  scraper:
    build:
      context: ./back-end
      dockerfile: scraper/Dockerfile.production
      args:
        - BUILD_ENV=production
    container_name: comfyrent-scraper
    env_file:
      - .env.production
    environment:
      # Database connection
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=comfyrent_production
      - POSTGRES_USER=comfyrent_user
      # Logging
      - LOG_LEVEL=INFO
      # Optimized scraper settings
      - MAX_CONCURRENT_SCRAPERS=2
      - BATCH_SIZE=20
      - SCRAPE_DELAY=1
    secrets:
      - postgres_password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - comfyrent-network
    restart: unless-stopped
    volumes:
      - scraper_logs:/app/logs
      - scraper_data:/app/data
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.2'
        reservations:
          memory: 512M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Container handles startup automatically via Dockerfile

  # Multilingual Content Processor (Dedicated Worker)
  multilingual_worker:
    build:
      context: ./multilingual-worker
      dockerfile: Dockerfile
    environment:
      # Database connection (password read from secrets file)
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=comfyrent_production
      - POSTGRES_USER=comfyrent_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - DATABASE_URL=postgresql+asyncpg://comfyrent_user:oS05j2bk7uM7iBUGwHpJdOn8zMDncnMrpXJWfDAjtd0=@postgres:5432/comfyrent_production
      - API_TOKEN=dummy_token_placeholder
      # Optimized worker configuration
      - BATCH_SIZE=25
      - PROCESS_INTERVAL=180
      - MAX_RETRIES=3
      - LOG_LEVEL=INFO
      - DEBUG_MODE=false
      - WORKER_THREADS=2
    secrets:
      - postgres_password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - comfyrent-network
    restart: unless-stopped
    volumes:
      - multilingual_logs:/app/logs
      - ./multilingual-worker/logs:/app/logs
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.125'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Production Secrets
secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  minio_root_user:
    file: ./secrets/minio_root_user.txt
  minio_root_password:
    file: ./secrets/minio_root_password.txt
  jwt_secret_key:
    file: ./secrets/jwt_secret_key.txt
  redis_password:
    file: ./secrets/redis_password.txt

# Production Networks
networks:
  comfyrent-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Production Volumes
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
  scraper_logs:
    driver: local
  scraper_data:
    driver: local
  multilingual_logs:
    driver: local
