# Advanced MyHome.ge Scraper Configuration

# Basic scraping settings
max_properties: 1000
batch_size: 50
delay_between_requests: 0.1
max_retries: 3
timeout: 30
cleanup_days: 30

# Feature toggles
concurrent_languages: true
enable_image_download: false
enable_deduplication: true
enable_owner_priority: true

# Rate limiting
rate_limit_per_minute: 600

# Storage paths (inside container)
image_storage_path: "/app/data/property_images"
log_directory: "/app/logs"
reports_directory: "/app/data/reports"

# Database connection (will use environment variables)
database_url: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/real_estate_db"

# User agents for rotation
user_agents:
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"

# API endpoints
api_endpoints:
  list_properties: "https://api-statements.tnet.ge/v1/statements"
  property_details: "https://api.myhome.ge/v1/statements"
  
# Property type mappings
property_types:
  1: "apartment"
  2: "house"
  3: "commercial"
  4: "country_house"
  5: "land_plot"
  6: "hotel"

# Deal type mappings
deal_types:
  1: "sale"
  2: "rent"
  3: "lease"
  7: "daily_rent"

# Currency mappings
currencies:
  1: "USD"
  2: "GEL"
  3: "EUR"

# Exchange rates (fallback values)
exchange_rates:
  USD_GEL: 2.71
  EUR_GEL: 2.90
  EUR_USD: 1.07
  USD_EUR: 0.93

# Validation settings
validation:
  # Georgian coordinate bounds
  min_latitude: 40.0
  max_latitude: 43.6
  min_longitude: 39.8
  max_longitude: 46.7
  
  # Price validation ranges
  price_ranges:
    USD:
      min: 50
      max: 50000
    GEL:
      min: 135
      max: 135000
    EUR:
      min: 45
      max: 45000

# Deduplication settings
deduplication:
  similarity_threshold: 0.85
  coordinate_precision: 0.0001
  owner_indicators:
    - "owner"
    - "individual"
    - "private"
    - "person"
  agency_indicators:
    - "agency"
    - "realtor"
    - "broker"
    - "company"

# Languages for multilingual support
languages:
  - "ka"  # Georgian
  - "en"  # English
  - "ru"  # Russian

# Monitoring and alerting
monitoring:
  health_check_interval: 300  # seconds
  error_threshold: 10  # percentage
  memory_threshold: 1024  # MB
  
# Scheduling (for cron jobs)
scheduling:
  full_scrape_cron: "0 2 * * *"  # Daily at 2 AM
  incremental_cron: "0 */6 * * *"  # Every 6 hours
  cleanup_cron: "0 3 * * 0"  # Weekly on Sunday at 3 AM
