services:
  multilingual-worker:
    build: .
    container_name: multilingual-worker
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@postgres:5432/real_estate_db
      - API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ2IjoxLCJpYXQiOjE3NTQzODU3NjksImV4cGlyZXNfYXQiOjE3NTQzODY0MjksImRhdGEiOnsidXNlcl9pZCI6NTEwNTQzMywidXNlcm5hbWUiOiJrYXhhbWlxZWxhZHplQGdtYWlsLmNvbSIsInNlc3Npb25faWQiOiIzYzA2NjE4YjU0NGMyMTI4MTBkN2NhYjRhMDQ1Mzk5MDFlYThmZDljNWEwN2FhMWE3ZmI4NTdhMTdlOWVjNGZiIiwibGl2b191c2VyX2lkIjpudWxsLCJzd29vcF91c2VyX2lkIjozODQxNjAsInRrdF91c2VyX2lkIjpudWxsLCJnZW5kZXJfaWQiOjEsImJpcnRoX3llYXIiOjE5NzgsImJpcnRoX2RhdGUiOiIxOTc4LTA4LTAxIiwicGhvbmUiOiI1OTk3MzgwMjMiLCJ1c2VyX25hbWUiOiJrYXhhIiwidXNlcl9zdXJuYW1lIjoibWlxZWxhZHplIiwidHlwZV9pZCI6MH19.DES3OMjLem3W0em42vnxoSEYOAq4jLEAjjjixvRyqDJT0bQHd30wFqqjSrSfGH9iLZkMp0gtrXiVFJGV_RlWTlTvwfQCVzZM4H58dS-nescI2DZy4CZdTF9u45nWtgxXxhnz9Kk0gbHaVtqXHu1rUnxLJQoGc9g1k0JSH_Y9xDPoBbsNmqivRu5E7BXkh2Q6eXXL6BuCxWRxaNeD7pJ8dQmrEt4HVOoqTvMD_TiHE-dvgf5RqQRK7q3JOd4f-niXIKwjgn1JCCU3WUPUhvjEiCR_lV-OmyB_3IHCxoDcNr7sT48fBvYYsYLOhrjZVbUNVdmPO0JZFUIskq_6vWG3dw
      - LOG_LEVEL=INFO
      - BATCH_SIZE=50
      - PROCESS_INTERVAL=300
      - MAX_RETRIES=3
      - DEBUG_MODE=false
    volumes:
      - ./logs:/app/logs
    networks:
      - real_estate_deployment_comfyrent-network
    depends_on:
      - postgres
    restart: unless-stopped
    profiles:
      - multilingual

  postgres:
    image: postgres:15
    container_name: multilingual-postgres
    environment:
      - POSTGRES_DB=real_estate_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - real_estate_deployment_comfyrent-network
    restart: unless-stopped
    profiles:
      - multilingual

volumes:
  postgres_data:

networks:
  real_estate_deployment_comfyrent-network:
    external: true
